
package FamousPhilosophers;

import java.awt.Color;
import java.awt.Toolkit;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *<pre>
 * Class        AddPhilosopher
 * File         AddPhilosopher.java
 * Project      Famous Philosophers
 * Description  A class uses to add new Philosophers
 * Platform     jdk 1.8.0_214; NetBeans IDE 11.3; Windows 10
 * Course       CS 142, Edmonds Community College
 * Date         1/27/2021
 * History log  1/10/2021, 1/20/2021
 * @author	<i>Nguyen Vi Cao</i>
 * @version 	%1% %2%
 * @see     	java.awt.Color
 * @see         java.awt.Toolkit
 *</pre>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class AddPhilosopher extends javax.swing.JDialog 
{
    private Philosopher newPhilosopher;         //Philosopher to be created
    private boolean error = false;              //checking for errors in input
    private String errorMessage = "";           //error message
    private final int MAX_YEAR = 2021;          //Maximum year 
    private final Color white = Color.WHITE;    //default background color for input textfield
    private final Color pink = Color.PINK;      //background color for bad input textfield
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Constructor     AddPhilosopher()
     * Description     Create an instance of the GUI form , set the default
     *                 JButton to be saveJButton, set icon image, centers form,
     *                 and sets the JDialog form to modal
     * @param          parent java.awt.Frame
     * @param          modal boolean
     * @author         <i>Nguyen Vi Cao</i>
     * Date            1/27/2021
     * History log     1/10/2021, 1/20/2021
     *</pre>
     *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/  
    public AddPhilosopher(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(saveJButton);
        //set icon
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Images/800px-Raffaello_Scuola_di_Atene_numbered.svg"));
        //centers form
        this.setLocationRelativeTo(null);
        nameJTextField.requestFocus();
        newPhilosopher = null;
        setAlwaysOnTop(true);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJPanel = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        displayJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        placeJLabel = new javax.swing.JLabel();
        placeJTextField = new javax.swing.JTextField();
        yearJLabel = new javax.swing.JLabel();
        yearJTextField = new javax.swing.JTextField();
        workJLabel = new javax.swing.JLabel();
        workJTextField = new javax.swing.JTextField();
        synopsisJLabel = new javax.swing.JLabel();
        sypnosisJTextField = new javax.swing.JTextField();
        linkJLabel = new javax.swing.JLabel();
        linkJTextField = new javax.swing.JTextField();
        cancelJButton = new javax.swing.JButton();
        saveJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new Philosopher");
        setResizable(false);

        titleJLabel.setFont(new java.awt.Font("Tempus Sans ITC", 2, 30)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(51, 0, 0));
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("Add New Phiolosopher");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Philosophers.jpg"))); // NOI18N

        javax.swing.GroupLayout titleJPanelLayout = new javax.swing.GroupLayout(titleJPanel);
        titleJPanel.setLayout(titleJPanelLayout);
        titleJPanelLayout.setHorizontalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleJPanelLayout.setVerticalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        displayJPanel.setLayout(new java.awt.GridLayout(6, 2, 3, 3));

        nameJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameJLabel.setText("Name of philosopher");
        displayJPanel.add(nameJLabel);

        nameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJTextFieldFocusLost(evt);
            }
        });
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        displayJPanel.add(nameJTextField);

        placeJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        placeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placeJLabel.setText("Birth Place");
        displayJPanel.add(placeJLabel);

        placeJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        placeJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                placeJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(placeJTextField);

        yearJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearJLabel.setText("Year Born");
        displayJPanel.add(yearJLabel);

        yearJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(yearJTextField);

        workJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        workJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workJLabel.setText("Major Work");
        displayJPanel.add(workJLabel);

        workJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        workJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                workJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(workJTextField);

        synopsisJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        synopsisJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        synopsisJLabel.setText("Sypnopsis");
        displayJPanel.add(synopsisJLabel);

        sypnosisJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sypnosisJTextField.setAutoscrolls(false);
        sypnosisJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sypnosisJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(sypnosisJTextField);

        linkJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        linkJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkJLabel.setText("Link to YouTube");
        displayJPanel.add(linkJLabel);

        linkJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        linkJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                linkJTextFieldFocusLost(evt);
            }
        });
        displayJPanel.add(linkJTextField);

        cancelJButton.setMnemonic('c');
        cancelJButton.setText("Cancel");
        cancelJButton.setToolTipText("Dispose form");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        saveJButton.setMnemonic('s');
        saveJButton.setText("Save");
        saveJButton.setToolTipText("Save new Opera");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(displayJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed

    }//GEN-LAST:event_nameJTextFieldActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        cancelJButtonActionPerformed()
    * Description   Event handler to cancel adding a new opera: do nothing and
    *               leave newOpera as null
    * @param        evt ActionWvent
    * @see          java.awt.event.ActionEvent
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        saveJButtonActionPerformed()
    * Description   Event handler to create a new opera provided data inputed
    *               are valid
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        //local variables needed
        String name = "";
        String place = "";
        int year = 0;
        String work = "";
        String sypnosis = "";
        String link = "";
        
        //read all inputs as strings
        String philosopherName = nameJTextField.getText();
        String Place = placeJTextField.getText();
        String Year = yearJTextField.getText();
        String Work = workJTextField.getText();
        String Sypnosis = sypnosisJTextField.getText();
        String Link = linkJTextField.getText();
        //call appropriate Validation methods to verify input
        if (!Validation.isValidName(philosopherName))
        {
            errorMessage += "Invalid Philosopher Name\n";
            nameJTextField.requestFocus();
            error = true;
            nameJTextField.setToolTipText(nameJTextField.getToolTipText() + 
                    "--Invalid Philosopher Name");
        }
        else if(!Validation.isValidName(Place))
        {
            errorMessage += "Invalid Place\n";
            placeJTextField.requestFocus();
            error = true;
            placeJTextField.setToolTipText(nameJTextField.getToolTipText() + 
                    "--Invalid place");
        }
        else if(!Validation.isInteger(Year))
        {
            errorMessage += "Invalid Year\n";
            yearJTextField.requestFocus();
            error = true;
            yearJTextField.setToolTipText(nameJTextField.getToolTipText() + 
                    "--Invalid Year");
        }
        else if(!Validation.isValidText(Work))
        {
            errorMessage += "Invalid Major Work\n";
            workJTextField.requestFocus();
            error = true;
            workJTextField.setToolTipText(nameJTextField.getToolTipText() + 
                    "--Invalid Major Work");
        }
        else if(!Validation.isValidText(Sypnosis))
        {
            errorMessage += "Invalid Sypnosis\n";
            sypnosisJTextField.requestFocus();
            error = true;
            sypnosisJTextField.setToolTipText(nameJTextField.getToolTipText() + 
                    "--Invalid Sypnosis");
        }
        else if(!Validation.isValidURL(Link))
        {
            errorMessage += "Invalid Link\n";
            linkJTextField.requestFocus();
            error = true;
            linkJTextField.setToolTipText(nameJTextField.getToolTipText() + 
                    "--Invalid Link");
        }
        else 
            error = false;
        if(!error)
        {
            try
            {
                name = nameJTextField.getText();
                place = placeJTextField.getText();
                year = Integer.parseInt(yearJTextField.getText());
                work = workJTextField.getText();
                sypnosis = sypnosisJTextField.getText();
                link = linkJTextField.getText();
                newPhilosopher = new Philosopher(name, place, year, work, sypnosis, link);
                this.dispose();
            }
            catch (Exception ex)
            {
                throw new RuntimeException ("Error parsing input");
            }
        }
    }//GEN-LAST:event_saveJButtonActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        nameJTextFieldFocusLost()
    * Description   Event handler for the nameJTextField. It changes 
    *               color if input is not valid.
    * @param        evt FocusEvent
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void nameJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJTextFieldFocusLost
        //set background textfiled color
        String input = nameJTextField.getText();
        if(Validation.isValidName(input))
            nameJTextField.setBackground(white);
        else
            nameJTextField.setBackground(pink);
    }//GEN-LAST:event_nameJTextFieldFocusLost

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        placeJTextFieldFocusLost()
    * Description   Event handler for the composerJTextField. It changes 
    *               color if input is not valid.
    * @param        evt FocusEvent
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void placeJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_placeJTextFieldFocusLost
        //set background textfiled color
        String input = placeJTextField.getText();
        if(Validation.isValidName(input))
            placeJTextField.setBackground(white);
        else
            placeJTextField.setBackground(pink);
    }//GEN-LAST:event_placeJTextFieldFocusLost

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        yearJTextFieldFocusLost()
    * Description   Event handler for the yearJTextField. It changes 
    *               color if input is not valid.
    * @param        evt FocusEvent
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void yearJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearJTextFieldFocusLost
        //set background textfiled color
        String input = yearJTextField.getText();
        if(Validation.isInteger(input))
            yearJTextField.setBackground(white);
        else
            yearJTextField.setBackground(pink);
    }//GEN-LAST:event_yearJTextFieldFocusLost

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        workJTextFieldFocusLost()
    * Description   Event handler for the workJTextField. It changes 
    *               color if input is not valid.
    * @param        evt FocusEvent
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void workJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_workJTextFieldFocusLost
        //set background textfiled color
        String input = workJTextField.getText();
        if(Validation.isValidText(input))
            workJTextField.setBackground(white);
        else
            workJTextField.setBackground(pink);
    }//GEN-LAST:event_workJTextFieldFocusLost

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        sypnosisJTextFieldFocusLost()
    * Description   Event handler for the sypnosisJTextField. It changes 
    *               color if input is not valid.
    * @param        evt FocusEvent
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void sypnosisJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sypnosisJTextFieldFocusLost
        //set background textfiled color
        String input = sypnosisJTextField.getText();
        if(Validation.isValidText(input))
            sypnosisJTextField.setBackground(white);
        else
            sypnosisJTextField.setBackground(pink);
    }//GEN-LAST:event_sypnosisJTextFieldFocusLost

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        linkJTextFieldFocusLost()
    * Description   Event handler for the linkJTextField. It changes 
    *               color if input is not valid.
    * @param        evt FocusEvent
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void linkJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_linkJTextFieldFocusLost
        //set background textfiled color
        String input = linkJTextField.getText();
        if(Validation.isValidURL(input))
            linkJTextField.setBackground(white);
        else
            linkJTextField.setBackground(pink);
    }//GEN-LAST:event_linkJTextFieldFocusLost

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        getPhilosopher()
    * Description   get method to return getPhilosopher
    * @return       getOpera Opera
    * @author       <i>Nguyen Vi Cao</i>
    * Date          1/27/2021
    * History log   1/10/2021, 1/20/2021
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public Philosopher getPhilosopher()
    {
        return newPhilosopher;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel linkJLabel;
    private javax.swing.JTextField linkJTextField;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel placeJLabel;
    private javax.swing.JTextField placeJTextField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel synopsisJLabel;
    private javax.swing.JTextField sypnosisJTextField;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JPanel titleJPanel;
    private javax.swing.JLabel workJLabel;
    private javax.swing.JTextField workJTextField;
    private javax.swing.JLabel yearJLabel;
    private javax.swing.JTextField yearJTextField;
    // End of variables declaration//GEN-END:variables
}
